
CREATE TABLE IF NOT EXISTS PLATFORM_USER (
    NAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS CHAT(
    ID SERIAL PRIMARY KEY,
    USER1 VARCHAR(50) NOT NULL,
    USER2 VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER1) REFERENCES PLATFORM_USER(NAME),
    FOREIGN KEY (USER2) REFERENCES PLATFORM_USER(NAME)
);
CREATE TABLE IF NOT EXISTS MESSAGE(
    ID SERIAL PRIMARY KEY,
    MESSAGE VARCHAR(255) NOT NULL,
    CHAT_ID INTEGER NOT NULL,
    SENDER VARCHAR(50) NOT NULL,
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT(ID),
    FOREIGN KEY (SENDER) REFERENCES PLATFORM_USER(NAME)
);


